title: <p align="center"> Nurdin Sulaeman </p>

logo: "/images/profile pict.png?raw=true"

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/nurdinsulaeman/">LinkedIn</a> |
  <a href="https://github.com/nurdinsulaemann">GitHub</a>
  </p>
  
  <p align="justify">
  I enjoy working with data, discovering patterns and turning raw data into meaningful insights. 
  <br><br>
  I am currently working in the ecommerce industry, handling various data tasks, from web scraping to data processing and transformation.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
