title: <p align="center"> Nurdin Sulaeman </p>

logo: "/images/logo_200x200.png?raw=true"

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/nurdinsulaeman/">LinkedIn</a> |
  <a href="https://github.com/nurdinsulaemann">GitHub</a>
  </p>
  
  <p align="justify">
  I enjoy working with data, discovering patterns and turning raw data into meaningful insights. 
  <br><br>
  Currently, I work in the e-commerce industry, managing product data to keep it accurate and well-structured,  I also use web scraping to gather data from various sources, then transform it to uncover valuable insights.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
